version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 20
    groups:
      react:
        patterns:
          - "react"
          - "react-*"
          - "react-dom"
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
      linters:
        patterns:
          - "eslint"
          - "eslint-*"
          - "prettier"
          - "prettier-*"
      testing:
        patterns:
          - "jest"
          - "jest-*"
          - "@testing-library/*"
          - "vitest"
          - "cypress"
      build-tools:
        patterns:
          - "webpack"
          - "webpack-*"
          - "rollup"
          - "rollup-*"
          - "vite"
          - "vite-*"
          - "babel"
          - "babel-*"
          - "@babel/*"
      storybook:
        patterns:
          - "storybook"
          - "storybook-*"
          - "@storybook/*"
      three-js:
        patterns:
          - "three"
          - "three-*"
          - "@react-three/*"
