name: Update README on Merge to Main

on:
  pull_request:
    types: [closed]

jobs:
  update-readme:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update README to main
        run: |
          # Replace "tree/ANYTHING" with "tree/main" in README.md
          sed -i "s|tree/[^ ]*|tree/main|g" README.md

          # Stage & commit changes (if any)
          git add README.md
          git commit -m "chore: Update StackBlitz link to main after merging PR" || echo "No changes to commit"

      - name: Push changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          # Push the newly committed change back to 'main'
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git HEAD:main
